import type { Metadata } from 'next';
import { Inter, Playfair_Display, JetBrains_Mono } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from 'next-themes';
import { Toaster } from '@/components/ui/sonner';

const inter = Inter({
	subsets: ['latin'],
	variable: '--font-sans',
});

const playfair = Playfair_Display({
	subsets: ['latin'],
	variable: '--font-serif',
});

const jetbrains = JetBrains_Mono({
	subsets: ['latin'],
	variable: '--font-mono',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en' suppressHydrationWarning={true}>
			<body
				className={`${inter.variable} ${playfair.variable} ${jetbrains.variable} antialiased w-full`}
			>
				<ThemeProvider defaultTheme='dark'>
					<main className='min-h-screen bg-background'>{children}</main>
					<Toaster richColors position='top-right' />
				</ThemeProvider>
			</body>
		</html>
	);
}
