export interface Conversation {
  id?: number; // optional because it will be generated by the hook
  role: 'user' | 'model';
  message: string;
  send_time?: string; // optional because it will be generated by the hook
  timeLeft?: number; // Optional if role is 'user'
  category?: 'technical' | 'behavioral' | 'other'; // Optional if role is 'model'
  tips?: string; // Optional if role is 'model'
}
